import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

//Compent Imports
import Header from '../components/Header'

//Pages Import
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <div className='container mt-5'>
          <div className='row'>
            <div className='col text-center'>
            <Link href="/universidad">Uni</Link>
              <h1>
              Notas de estudio, resúmenes y respuestas gratuitas para sus estudios
              </h1>
              <p>Estudia más fácil, más rápido y mejor.</p>
            </div>
            <div className='row'>
              <div className='col'>
                <div className="input-group mb-3">
                  <input type="text" className="form-control" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1" />
                  <button className="btn btn-primary" type="button" id="button-addon1">Registrate Gratis!</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
